build-web:
	wasm-pack build --debug --target web --features web

run-web: build-web
	miniserve ./

build-sdl:
    cargo build --features sdl

build-sdl2:
    cargo build --features sdl2

run-sdl:
	cargo run --features sdl

run-sdl2:
	cargo run --features sdl2
