name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Update
        run: |
          sudo apt-get update
          sudo apt-get install -y \
                      build-essential cmake git ninja-build pkg-config \
                      libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev \
                      libwayland-dev libxkbcommon-dev wayland-protocols

      - name: Cache SDL3 build
        id: cache-sdl
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/SDL3/build
            ${{ github.workspace }}/SDL3/install
            key: ${{ runner.os }}-sdl3-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Clone SDL3 (if not cached)
        if: steps.cache-sdl.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/libsdl-org/SDL.git SDL3

      - name: Build & install SDL3 (if not cached)
        if: steps.cache-sdl.outputs.cache-hit != 'true'
        run: |
          cd SDL3
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/SDL3/install -DSDL_TESTS=OFF
          cmake --build build --parallel
          cmake --install build

      - name: Run tests SDL
        run: cargo test --features sdl --verbose

      - name: Build Web
        run: cargo build --features web --verbose

      - name: Run tests Web
        run: cargo test --features web --verbose
