name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install SDL3
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl3-dev

      - name: Run tests SDL
        run: cargo test --features sdl --verbose

      - name: Build Web
        run: cargo build --features web --verbose

      - name: Run tests Web
        run: cargo test --features web --verbose
